booster_offer:
    resource: "@BoosterBundle/Resources/config/routing/offer.yml"
    prefix:   /offer

booster_citizenfront:
    path:     /citizen
    defaults: { _controller: BoosterBundle:Default:citizen }

booster_actor:
    path:     /actor
    defaults: { _controller: BoosterBundle:Default:actor}

booster_homepage:
    path:     /
    defaults: { _controller: BoosterBundle:Default:home_page_no_connect }

booster_mayor:
    path:     /mayor
    defaults: { _controller: BoosterBundle:Default:mayor}

booster_registerMayor:
    path:     /mayor/register
    defaults: { _controller: BoosterBundle:Registration:mayorRegister}

booster_registerCitizen:
    path:     /citizen/register
    defaults: { _controller: BoosterBundle:Registration:citizenRegister}

booster_registerActor:
    path:     /actor/register
    defaults: { _controller: BoosterBundle:Registration:actorRegister}

