
booster_citizenfront:
    path:     /citizen
    defaults: { _controller: BoosterBundle:Default:citizen }

booster_actor:
    path:     /actor
    defaults: { _controller: BoosterBundle:Default:actor}

booster_homepage:
    path:     /
    defaults: { _controller: BoosterBundle:Default:home_page_no_connect }

booster_mayor:
    path:     /mayor
    defaults: { _controller: BoosterBundle:Default:mayor}

