booster_actorBack:
    resource: "@BoosterBundle/Resources/config/routing/actor.yml"
    prefix:   /actor

booster_mayorBack:
    resource: "@BoosterBundle/Resources/config/routing/mayor.yml"
    prefix:   /mayor

booster_citizeginBack:
    resource: "@BoosterBundle/Resources/config/routing/citizen.yml"
    prefix:   /citizen

booster_partners:
    resource: "@BoosterBundle/Resources/config/routing/partners.yml"
    prefix:   /partners

booster_expert:
    resource: "@BoosterBundle/Resources/config/routing/expert.yml"
    prefix:   /expert

booster_citizen:
    path:     /citizenfront/{id}
    defaults: { _controller: BoosterBundle:Default:citizen }

booster_actor:
    path:     /actorfront/{id}
    defaults: { _controller: BoosterBundle:Default:actor}

booster_homepage:
    path:     /
    defaults: { _controller: BoosterBundle:Default:home_page_no_connect }

booster_mayor:
    path:     /mayorfront/{id}
    defaults: { _controller: BoosterBundle:Default:mayor}

booster_registerMayor:
    path:     /mayor/register
    defaults: { _controller: BoosterBundle:Registration:mayorRegister}

booster_registerCitizen:
    path:     /citizen/register
    defaults: { _controller: BoosterBundle:Registration:citizenRegister}

booster_registerActor:
    path:     /actor/register
    defaults: { _controller: BoosterBundle:Registration:actorRegister}

booster_admin:
    path:     /admin/
    defaults: { _controller: BoosterBundle:Default:admin}





