booster_actorBack:
    resource: "@BoosterBundle/Resources/config/routing/actor.yml"
    prefix:   /actor

booster_mayorBack:
    resource: "@BoosterBundle/Resources/config/routing/mayor.yml"
    prefix:   /mayor

booster_citizenBack:
    resource: "@BoosterBundle/Resources/config/routing/citizen.yml"
    prefix:   /citizen

booster_offer:
    resource: "@BoosterBundle/Resources/config/routing/actor.yml"
    prefix:   /actor

booster_citizenfront:
    path:     /citizenfront
    defaults: { _controller: BoosterBundle:Default:citizen }

booster_actor:
    path:     /actorfront
    defaults: { _controller: BoosterBundle:Default:actor}

booster_homepage:
    path:     /
    defaults: { _controller: BoosterBundle:Default:home_page_no_connect }

booster_mayor:
    path:     /mayorfront
    defaults: { _controller: BoosterBundle:Default:mayor}

booster_registerMayor:
    path:     /mayor/register
    defaults: { _controller: BoosterBundle:Registration:mayorRegister}

booster_registerCitizen:
    path:     /citizen/register
    defaults: { _controller: BoosterBundle:Registration:citizenRegister}

booster_registerActor:
    path:     /actor/register
    defaults: { _controller: BoosterBundle:Registration:actorRegister}





