BoosterBundle\Entity\Needs:
    type: entity
    table: null
    repositoryClass: BoosterBundle\Repository\NeedsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        cp:
            type: string
            length: 255
        town:
            type: string
            length: 255
        description:
            type: text
        activity:
            type: string
            length: 255
            nullable: true
        availability:
            type: string
            length: 255
            nullable: true
        lat:
            type: integer
            nullable: true
        lgt:
            type: integer
            nullable: true

        image2:
            type: string
            length: 255
            nullable: true

        image3:
            type: string
            length: 255
            nullable: true

    manyToOne:
        users:
            targetEntity: BoosterBundle\Entity\User
            inversedBy: Id

    lifecycleCallbacks:

      prePersist: [preUpload2, preUpload3]
      preUpdate: [preUpload2, preUpload3]
      postPersist: [upload2, upload3]
      postUpdate: [upload2, upload2]
      postRemove: [removeUpload2, removeUpload2]

