citizen_index:
    path:     /
    defaults: { _controller: "BoosterBundle:ProfCitizen:index" }
    methods:  GET

citizen_showOffer:
    path:     /offer/{id}/show
    defaults: { _controller: "BoosterBundle:ProfCitizen:showOffer" }
    methods:  GET

citizen_newOffer:
    path:     /offer/new
    defaults: { _controller: "BoosterBundle:ProfCitizen:newOffer" }
    methods:  [GET, POST]

citizen_editOffer:
    path:     /offer/{id}
    defaults: { _controller: "BoosterBundle:ProfCitizen:editOffer" }
    methods:  [GET, POST]

citizen_deleteOffer:
    path:     /offer/{id}/delete
    defaults: { _controller: "BoosterBundle:ProfCitizen:deleteOffer" }
    methods:  [GET, POST]


citizen_showNeeds:
    path:     /needs/{id}/show
    defaults: { _controller: "BoosterBundle:ProfCitizen:showNeed" }
    methods:  GET

citizen_newNeeds:
    path:     /needs/new
    defaults: { _controller: "BoosterBundle:ProfCitizen:newNeed" }
    methods:  [GET, POST]

citizen_editNeeds:
    path:     /needs/{id}
    defaults: { _controller: "BoosterBundle:ProfCitizen:editNeed" }
    methods:  [GET, POST]

citizen_deleteNeeds:
    path:     /needs/{id}/delete
    defaults: { _controller: "BoosterBundle:ProfCitizen:deleteNeeds" }
    methods:  [GET, POST]

