expert_index:
    path:     /
    defaults: { _controller: "BoosterBundle:Expert:index" }
    methods:  GET

expert_admin:
    path:     /admin
    defaults: { _controller: "BoosterBundle:Expert:admin" }
    methods:  GET

expert_show:
    path:     /{id}/show
    defaults: { _controller: "BoosterBundle:Expert:show" }
    methods:  GET

expert_new:
    path:     /new
    defaults: { _controller: "BoosterBundle:Expert:new" }
    methods:  [GET, POST]

expert_edit:
    path:     /edit/{id}
    defaults: { _controller: "BoosterBundle:Expert:edit" }
    methods:  [GET, POST]

expert_delete:
    path:     /{id}/delete
    defaults: { _controller: "BoosterBundle:Expert:delete" }
    methods:  [GET, POST]
