mayor_index:
    path:     /profile
    defaults: { _controller: "BoosterBundle:ProfMayor:index" }
    methods:  GET

mayor_showOffer:
    path:     /offer/{id}/show
    defaults: { _controller: "BoosterBundle:ProfMayor:showOffer" }
    methods:  GET

mayor_newOffer:
    path:     /offer/new
    defaults: { _controller: "BoosterBundle:ProfMayor:newOffer" }
    methods:  [GET, POST]

mayor_editOffer:
    path:     /offer/{id}/edit
    defaults: { _controller: "BoosterBundle:ProfMayor:editOffer" }
    methods:  [GET, POST]

mayor_listOffer:
    path:     /offer/list
    defaults: { _controller: "BoosterBundle:ProfMayor:listOfferMayor" }
    methods:  [GET, POST]

mayor_deleteOffer:
    path:     /offer/{id}/delete
    defaults: { _controller: "BoosterBundle:ProfMayor:deleteOffer" }
    methods:  [GET, POST]

mayor_showNeeds:
    path:     /needs/{id}/show
    defaults: { _controller: "BoosterBundle:ProfMayor:showNeed" }
    methods:  GET

mayor_newNeeds:
    path:     /needs/new
    defaults: { _controller: "BoosterBundle:ProfMayor:newNeed" }
    methods:  [GET, POST]

mayor_editNeeds:
    path:     /needs/{id}/edit
    defaults: { _controller: "BoosterBundle:ProfMayor:editNeed" }
    methods:  [GET, POST]

mayor_deleteNeeds:
    path:     /needs/{id}/delete
    defaults: { _controller: "BoosterBundle:ProfMayor:deleteNeeds" }
    methods:  [GET, POST]

mayor_listNeed:
    path:     /needs/list
    defaults: { _controller: "BoosterBundle:ProfMayor:listNeedsMayor" }
    methods:  [GET, POST]

mayor_list:
    path:     /list
    defaults: { _controller: "BoosterBundle:ProfMayor:listMayor" }

mayor_editDescription:
    path:  description/{id}
    defaults: { _controller: "BoosterBundle:ProfMayor:editDescription" }
    methods:  [GET, POST]

mayor_editUser:
    path:     /user/{id}
    defaults: { _controller: "BoosterBundle:ProfMayor:editUser" }
    methods:  [GET, POST]

mayor_editWordMayor:
    path:     /wordMayor/{id}
    defaults: { _controller: "BoosterBundle:ProfMayor:editWordMayor" }
    methods:  [GET, POST]

