mayor_index:
    path:     /
    defaults: { _controller: "BoosterBundle:ProfMayor:index" }
    methods:  GET

mayor_showOffer:
    path:     /offer/{id}/show
    defaults: { _controller: "BoosterBundle:ProfMayor:showOffer" }
    methods:  GET

mayor_newOffer:
    path:     /offer/new
    defaults: { _controller: "BoosterBundle:ProfMayor:newOffer" }
    methods:  [GET, POST]

mayor_editOffer:
    path:     /offer/{id}
    defaults: { _controller: "BoosterBundle:ProfMayor:editOffer" }
    methods:  [GET, POST]

mayor_deleteOffer:
    path:     /offer/{id}/delete
    defaults: { _controller: "BoosterBundle:ProfMayor:deleteOffer" }
    methods:  [GET, POST]


mayor_showNeeds:
    path:     /needs/{id}/show
    defaults: { _controller: "BoosterBundle:ProfMayor:showNeed" }
    methods:  GET

mayor_newNeeds:
    path:     /needs/new
    defaults: { _controller: "BoosterBundle:ProfMayor:newNeed" }
    methods:  [GET, POST]

mayor_editNeeds:
    path:     /needs/{id}
    defaults: { _controller: "BoosterBundle:ProfMayor:editNeed" }
    methods:  [GET, POST]

mayor_deleteNeeds:
    path:     /needs/{id}/delete
    defaults: { _controller: "BoosterBundle:ProfMayor:deleteNeeds" }
    methods:  [GET, POST]

mayor_listNeed:
    path:     /needs/list
    defaults: { _controller: "BoosterBundle:ProfMayor:listNeedsMayor" }
    methods:  [GET, POST]

